config/routes.rb
Rails.application.routes.draw do

  match "/_graffity" => "inspector#index"
  match '/_graffity/coderay/:id' => 'inspector#coderay', :as => :coderay
  match '/_graffity/current_items' => 'inspector#current_items', :as => :inspect_current_items
end

app/models/graffity/action.rb
class Graffity::Action < Sequel::Model(:actions)
end

app/models/graffity/template.rb
class Graffity::Template < Sequel::Model(:templates)
end

app/controllers/inspector_controller.rb
require 'coderay'
class InspectorController < ApplicationController
  layout "graffity_layout"

  def index
  end

  def current_items
    graffity_action = Graffity::Action.reverse_order(:start).first
    if graffity_action
      @title = "#{graffity_action.controller}##{graffity_action.name}"
      @graffity_template = Graffity::Template.where(:req_id => graffity_action.req_id, :partial => false).first
      @graffity_partials = Graffity::Template.where(:req_id => graffity_action.req_id, :partial => true)
    end
    render :current_items, :layout => false
  end

  def coderay
    @graffity_template = Graffity::Template.where(:id => params[:id]).first
    render :coderay, :layout => false
  end

end

app/views/inspector/coderay.html.erb
<h4><%= @graffity_template.virtual_path %></h4>
<%= CodeRay.highlight_file(@graffity_template.identifier, :lang => :ruby).html_safe %>

app/views/inspector/current_items.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Layout</li>
    <li><a href="<%=coderay_path(@graffity_template.id)%>" data-toggle="modal" data-target="#myModal"><%= @graffity_template.layout %></a>
      <ul class="nav nav-list">
        <li class="nav-header">Overrides</li>
        <% for override in Deface::Override.find({:virtual_path => @graffity_template.layout }) -%>
          <li><a href="#"><%= override.name %></a></li>
        <% end -%>
      </ul>
    </li>
    <li class="nav-header">Template</li>
    <li><a href="<%=coderay_path(@graffity_template.id)%>" data-toggle="modal" data-target="#myModal"><%= @graffity_template.virtual_path %></a>
      <% if Deface::Override.find({:virtual_path => @graffity_template.virtual_path }).count > 0%>
        <ul class="nav nav-list">
          <li class="nav-header">Overrides</li>
          <% for override in Deface::Override.find({:virtual_path => @graffity_template.virtual_path }) -%>
            <li><a href="#"><%= override.name %></a></li>
          <% end -%>
        </ul>
      <% end %>
    </li>
    <li class="nav-header">Partials</li>
    <% for partial in @graffity_partials -%>
      <li><a href="<%=coderay_path(partial.id)%>" data-toggle="modal" data-target="#myModal"><%= partial.virtual_path %></a>

        <% if Deface::Override.find({:virtual_path => partial.virtual_path }).count > 0%>
          <ul class="nav nav-list">
            <li class="nav-header">Overrides</li>
            <% for override in Deface::Override.find({:virtual_path => partial.virtual_path }) -%>
              <li><a href="#"><%= override.name %></a></li>
            <% end -%>
          </ul>
        <% end %>
      </li>
    <% end -%>
  </ul>
</div><!--/.well -->

<div id="myModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>View information</h3>
  </div>
  <div class="modal-body" style="overflow:auto">
  </div>
</div>

app/views/layouts/graffity_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graffify</title>

  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css" rel="stylesheet">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>

  <style>
    html {
      height: 100%;
    }

    body {
      padding: 0;
      margin: 0;
      height: 100%;
    }

    iframe{
      width: 100%;
      height: 100%;
      border: none;
    }

    .sidebar-nav {
        padding: 9px 0;
    }

    a.toggles {
        position:fixed;
        left:0;
        top:0;
        display:block;
        background-color:black;
        color:white;
        padding:10px 20px;
    }

    #content{
      margin-left:0px;
    }
    #sidebar {
      margin-top:50px;
    }
  </style>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div id="sidebar" class="span3" style="display:none">
    </div><!--/span-->
    <a href="#" class="toggles"><i class="icon-chevron-right"></i></a>
    <div id="content" class="span12">
      <iframe id="spree_frame" src="/"></iframe>
    </div>
  </div>
</div><!--/.fluid-container-->​

<script type="text/javascript">

  $('a.toggles').click(function() {
    $('a.toggles i').toggleClass('icon-chevron-right icon-chevron-left');
    $('#sidebar').animate({ width: 'toggle' }, 100);
    $('#content').toggleClass('span9 span12');
  });

  $('#content').toggle(
    function() {
      $(this).css({
        'margin-left': '0'
      });
    }, function() {
      $(this).css({
        'margin-left': '2.127659574%'
      });
    });

    $("#spree_frame").load(function (){
      $("#sidebar").load("<%=inspect_current_items_path%>", function(response, status, xhr) {});
    });

</script>

</body>
</html>